//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18449
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DayInfo.Europe.Resources {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Belgium {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Belgium() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DayInfo.Europe.Resources.Belgium", typeof(Belgium).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The armistice between the Allies and Germany – also known as the &quot;Armistice of Compiègne&quot; after the location it was signed – was the agreement that ended the fighting in western Europe that comprised the First World War. It went into effect at 11 a.m. on 11 November 1918, and marked a victory for the Allies and a complete defeat for Germany, although not technically a surrender. The Germans were responding to the policies proposed by American president Woodrow Wilson in his Fourteen Points of January 1918.  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ArmisticeDescription {
            get {
                return ResourceManager.GetString("ArmisticeDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://en.wikipedia.org/wiki/First_Armistice_at_Compi%C3%A8gne.
        /// </summary>
        internal static string ArmisticeLink {
            get {
                return ResourceManager.GetString("ArmisticeLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wikipedia:http://en.wikipedia.org/wiki/First_Armistice_at_Compi%C3%A8gne.
        /// </summary>
        internal static string ArmisticeLinks {
            get {
                return ResourceManager.GetString("ArmisticeLinks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Armistice at Compiègne.
        /// </summary>
        internal static string ArmisticeTitle {
            get {
                return ResourceManager.GetString("ArmisticeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Labour Day (Labor Day in the USA) is an annual holiday to celebrate the achievements of workers. Labour Day has its origins in the labour union movement, specifically the eight-hour day movement, which advocated eight hours for work, eight hours for recreation, and eight hours for rest. For many countries, Labour Day is synonymous with, or linked with, International Workers&apos; Day, which occurs on 1 May. For other countries, Labour Day is celebrated on a different date, often one with special significance for [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string LabourDayDescription {
            get {
                return ResourceManager.GetString("LabourDayDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://en.wikipedia.org/wiki/Labour_Day.
        /// </summary>
        internal static string LabourDayLink {
            get {
                return ResourceManager.GetString("LabourDayLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Labour Day.
        /// </summary>
        internal static string LabourDayTitle {
            get {
                return ResourceManager.GetString("LabourDayTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The festival&apos;s establishment dates to a law of 27 May 1890[2] and commemorates an event on 21 July 1831 in which Leopold of Saxe-Cobourg swore allegiance to the new Belgian constitution, thus becoming the first &quot;King of the Belgians&quot;.[1] The king&apos;s vow marked the start of the independent state of Belgium under a constitutional monarchy and parliament..
        /// </summary>
        internal static string NationalDayDescription {
            get {
                return ResourceManager.GetString("NationalDayDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://en.wikipedia.org/wiki/Belgian_National_Day.
        /// </summary>
        internal static string NationalDayLink {
            get {
                return ResourceManager.GetString("NationalDayLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to National Day.
        /// </summary>
        internal static string NationalDayTitle {
            get {
                return ResourceManager.GetString("NationalDayTitle", resourceCulture);
            }
        }
    }
}
